### ISSUE TITLE
Option 4: `prepare(sound: )` seems to be missing as a view extension

### ISSUE THREAD

**Issue by joemdwills** [twostraws/Subsonic#11]
Hi Paul,

I found this project when working on adding sounds into one of my projects. After importing I thought about trying all options to see which suited my project. I believe there is a `View` extension missing for `prepare(sound: )`, which Option 4 suggests getting an `AVAudioPlayer` back to use as you see fit.

(Happy to raise as a PR) 

Thanks,
Joe

**PS:** HWS+ member, graduate of your two 100 Day courses, ex Mechanical Engineer, currently iOS Dev at John Lewis 😄 all thanks to you.

**Comment by twostraws** [comment]
Hello! Sorry for taking so long to get around to this – if that's a problem you're currently hitting, a PR to solve it would be most welcome. Thank you!

**Comment by joemdwills** [comment]
Done
